### ISSUE TITLE
Call a set of Km4City API and build an append only file for storing in DAF.

### ISSUE THREAD

**Issue by giux78** [italia/daf-replicate-ingestion#2]
Call a set of km4city APIs in a precise moment in space and time with a prefixed interval and build a csv or json file representing that moment in time and space. 

As an example
```
timestamp (depending on API call interval); Latitude, Longitude;Label; Descriptive string
3231231;45.43242:12.32131;Autobus 8;Pieno
31221311;453.43242:11.32131;Bici elettriche 8: Colonnine piazza electro
....................
```

Relevant Links:
- http://www.disit.org/drupal/?q=en-US/node/6852
- http://www.disit.org/6991

**Comment by ruphy** [comment]
Warning:
Due to a disastrous event, the API set is temporarly reduced. We thank Prof. Bellini for setting up the following interface: http://servicemap.km4city.org/WebAppGrafo/

This service will no longer provide access to real-time or changing data, and will only support the following API set:

Service search near GPS position
Service search near a service
Service search within a GPS area
Service search within a WKT described area
Service search within a stored WKT described area
Service search by municipality
Service search by query id
Full text search
Address/POI search by text
Address and geometry search by GPS
Generic Service
Parking service
Traffic sensor
Weather Forecast
Rating and comment API
Service Photo API
Last contributions API
Image caching API

**Comment by niclasek** [comment]
Hi, I'm in a team at hackathon in Firenze and we are working on this issue but need some help getting started. Do you have some starting point to give us?

**Comment by rasky** [comment]
@niclasek better to ask on Slack, channel #daf, and mention @ruphy

**Comment by jenkin** [comment]
This repo is now deprecated, issue closed.
