### ISSUE TITLE
Call Km4City's spatial API and create a web app with a map which allows for time exploration

### ISSUE THREAD

**Issue by giux78** [italia/daf-replicate-ingestion#3]
Call Km4City's spatial API, save the data, and build a "map" web application (you can base it off OpenstreetMap or Leaflet).
This application will save the data at different time intervals, and will provide the user with a bar or buttons for seeing the evolution of the datapoints in time.

Relevant links:
- http://www.disit.org/drupal/?q=en-US/node/6852
- http://www.disit.org/6991

**Comment by ruphy** [comment]
Warning:
Due to a disastrous event, the API set is temporarly reduced. We thank Prof. Bellini for setting up the following interface: http://servicemap.km4city.org/WebAppGrafo/

This service will no longer provide access to real-time or changing data, and will only support the following API set:

Service search near GPS position
Service search near a service
Service search within a GPS area
Service search within a WKT described area
Service search within a stored WKT described area
Service search by municipality
Service search by query id
Full text search
Address/POI search by text
Address and geometry search by GPS
Generic Service
Parking service
Traffic sensor
Weather Forecast
Rating and comment API
Service Photo API
Last contributions API
Image caching API

Since the data will not change until the datacenter has been restored, working on this task will be much harder.

**Comment by jenkin** [comment]
This repo is now deprecated, issue closed.
